name: Sophus
version: 1.26
date: 2022-08-05
description: |
    Computing in nilpotent Lie algebras

authors:
    - name: Csaba Schneider
      url: http://www.mat.ufmg.br/~csaba/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

needed-pkgs:
    - name: "autpgrp"
      version: "1.2"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/sophus/
readme: README
packageinfo: https://gap-packages.github.io/sophus/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sophus/releases/download/v1.26/sophus-1.26.tar.gz

abstract: |

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
