name: Sophus
version: 1.23
date: 2006-02-03
description: |
    Computing in nilpotent Lie algebras

authors:
    - name: Csaba Schneider
      url: http://www.sztaki.hu/~schneider

maintainers:
    - name: Csaba Schneider
      url: http://www.sztaki.hu/~schneider

GAP: ">= 4.7"

needed-pkgs:
    - name: "autpgrp"
      version: "1.2"
      url: "https://gap-packages.github.io/autpgrp/"

www: http://www.sztaki.hu/~schneider/Research/Sophus/
readme: README
packageinfo: http://www.sztaki.hu/~schneider/Research/Sophus/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.sztaki.hu/~schneider/Research/Sophus/sophus1r23.tar.gz

abstract: |
    http://www.sztaki.hu/~schneider/Research/Sophus/

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
