name: Sophus
version: "1.27"
license: "GPL-2.0-or-later"
date: 2022-08-09
description: |
    Computing in nilpotent Lie algebras

authors:
    - name: Csaba Schneider
      url: http://www.mat.ufmg.br/~csaba/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

needed-pkgs:
    - name: "autpgrp"
      version: "1.2"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/sophus/
readme: README
packageinfo: https://gap-packages.github.io/sophus/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sophus/releases/download/v1.27/sophus-1.27.tar.gz

abstract: |

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    nilpotent Lie algebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ST22</span>]   <b class='BibAuthor'>Schneider, C. and GAP Team, T.</b>,
     <i class='BibTitle'>Sophus, Computing in nilpotent Lie algebras,
             Version 1.27</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/sophus/">https://gap-packages.github.io/sophus/</a></span>.
    </p>
    

bibtex: |
    @misc{ Sophus1.27,
      author =           {Schneider, C. and GAP Team, T.},
      title =            {{Sophus},   Computing   in   nilpotent  Lie  algebras,
                          {V}ersion 1.27},
      month =            {Aug},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/sophus/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{sophus/}}},
      keywords =         {nilpotent Lie algebras},
      printedkey =       {ST22}
    }

